### ISSUE TITLE
Error when get username by command Get-JiraUser

### ISSUE THREAD

**Issue by Growlert** [AtlassianPS/JiraPS#411]
## Description
When I try to get user information from command like:
`Get-JiraUser -UserName 'some_user'`
It thows me the error:
```
Invoke-JiraMethod : The query parameter 'username' is not supported in GDPR strict mode.
C:\Program Files\WindowsPowerShell\Modules\JiraPS\2.14.0\JiraPS.psm1:2793 знак:34
+                     if ($users = Invoke-JiraMethod @parameter) {
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Invoke-JiraMethod], RuntimeException
    + FullyQualifiedErrorId : InvalidResponse.Status400,Invoke-JiraMethod
 
Get-JiraUser : No results when searching for user some_user
строка:1 знак:1
+ Get-JiraUser -UserName 'some_user'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-JiraUser
```

## Steps To Reproduce

Must use powershell module "JiraPS"

## Expected behavior

Should output the username information

## Your Environment

> ```powershell
> Get-Module JiraPS -ListAvailable | Select Name, Version
> $PSVersionTable
> ```

**Comment by friendlyneighbourhoodcoder** [comment]
It looks like Jira have been in the process of depreciating the "username" string on their API to order to comply with [European General Data Protection Regulation (GDPR)](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/)

[It's been replaced by the "query" string.](https://developer.atlassian.com/cloud/jira/platform/rest/v2/?_ga=2.184749033.1125548818.1587293447-1887864055.1568622269#api-rest-api-2-user-assignable-search-get)

We resolved this by altering the JiraPS module's Get-JiraUser function from:

`        $searchResourceUri = "$server/rest/api/2/user/search?username={0}"`
    `    $exactResourceUri = "$server/rest/api/2/user?username={0}"`


to:

`        $searchResourceUri = "$server/rest/api/2/user/search?query={0}"`
        `$exactResourceUri = "$server/rest/api/2/user?query={0}"`

**Comment by lipkau** [comment]
Hello @friendlyneighbourhoodcoder 
is the `query` query parameter valid for cloud server and on premise servers?

**Comment by friendlyneighbourhoodcoder** [comment]
Hi @lipkau 

Our organisation uses cloud server, so I can only confirm for cloud.

**Comment by ebekker** [comment]
The problem with user _references_ when calling against Jira Cloud is that Jira Cloud forces _GDPR mode_ and all API calls that reference a user account have to use an ID, not a name any more.

I propose adding an optional flag to `Set-JiraConfigServer` such as `-GdprMode` or something to that effect which will alter the behavior of all other methods so that anywhere that a user is referenced, instead of referring by name, the reference will be changed to ID.

And then of course all those areas across the module need to be updated to support this, which can be eased by centralizing that logic into a method such as `Resolve-JiraUserReference`.  If this approach is palatable to everyone, then I will try to work on and submit a PR to that effect.

**Comment by friendlyneighbourhoodcoder** [comment]
@ebekker - Sure thing, sounds like a plan!

**Comment by patrick-ryan1** [comment]
Is there a way to get the user list with ids?

**Comment by anhduck14** [comment]
> Is there a way to get the user list with ids?

According to the command based help, you can get all Jira users by
``` powershell
Get-JiraUser -UserName ""
```
_The empty string "" matches all users._

or use the REST API
```
<server>/rest/api/2/user/search?username=
```

**Comment by DamagedDingo** [comment]
Is this supposed to be fixed because I still get the error.

Get-JiraUser -UserName ""                                                   
Invoke-JiraMethod : The query parameter 'username' is not supported in GDPR strict mode.

**Comment by DamagedDingo** [comment]
> 
> 
> Is this supposed to be fixed because I still get the error.
> 
> Get-JiraUser -UserName ""
> Invoke-JiraMethod : The query parameter 'username' is not supported in GDPR strict mode.

Sorry ignore this. I had credential problems and it was throwing error 'No results when searching for user XXXXXX'

I used this fix and it worked after i fixed my other issue. 
$searchResourceUri = "$server/rest/api/2/user/search?query={0}"
$exactResourceUri = "$server/rest/api/2/user?query={0}"

Still trying to find a command that returns the whole object though inc all the fields in profile like Organization, Based in, email so that i can create a Insight customer (CI\Object) and link it to the Jira customer.

**Comment by jeffpatton1971** [comment]
So, this is still an issue with the specific cmdlet Get-JiraUser 2.14.6
```powershell
Get-Module JiraPS

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.14.6                JiraPS
```

This method does not work
```powershell
Get-JiraUser -UserName ""
Invoke-JiraMethod: The username or property query parameter must be provided
Invoke-JiraMethod:
Get-JiraUser: No results when searching for user
```

Specifying my email address also does not work
```powershell
Get-JiraUser -Username 'jeffrey.patton2@rackspace.com'
Invoke-JiraMethod: The query parameter 'username' is not supported in GDPR strict mode.
Invoke-JiraMethod:
Get-JiraUser: No results when searching for user jeffrey.patton2@###
```

**Comment by lipkau** [comment]
Fixed in v2.16: on Cloud, `Get-JiraUser` now uses `accountId` (`-AccountId` parameter / GDPR-strict-mode-safe lookups). `Update-Module JiraPS`. Closing.
